@baseUrl = http://localhost:5003

###inicio
GET {{baseUrl}}/

##-------------------------------------------------------------
### FUNCIONARIO

### Criar um Funcionário (Sem Foto):
POST {{baseUrl}}/funcionarios
Content-Type: multipart/form-data; boundary=---------------------------boundary123

-----------------------------boundary123
Content-Disposition: form-data; name="nome"

João Silva
-----------------------------boundary123--



###
### Criar um Funcionário com Foto
POST {{baseUrl}}/funcionarios
Content-Type: multipart/form-data; boundary=---------------------------boundary123

-----------------------------boundary123
Content-Disposition: form-data; name="nome"

João Silva
-----------------------------boundary123
Content-Disposition: form-data; name="foto"; filename="foto.jpg"
Content-Type: image/jpeg

< ./foto.jpg
-----------------------------boundary123--

### Buscar todos os Funcionários:
GET {{baseUrl}}/funcionarios

###Buscar um Funcionário por ID:
GET {{baseUrl}}/funcionarios/2

###Atualizar um Funcionário somente nome:
PUT {{baseUrl}}/funcionarios/2
Content-Type: multipart/form-data; boundary=---------------------------boundary123

-----------------------------boundary123
Content-Disposition: form-data; name="nome"

Carlos Silva Atualizado
-----------------------------boundary123--

###atualizar um funcionario com foto:
PUT http://localhost:5003/funcionarios/2
Content-Type: multipart/form-data; boundary=---------------------------boundary123

-----------------------------boundary123
Content-Disposition: form-data; name="nome"

Carlos Silva Atualizado
-----------------------------boundary123
Content-Disposition: form-data; name="foto"; filename="nova_foto.jpg"
Content-Type: image/jpeg

< ./nova_foto.jpg
-----------------------------boundary123--


###Deletar um Funcionário:
curl -X DELETE http://localhost:5003/funcionarios/2

##-------------------------------------------------------------
### PROJETO
### Criar um Projeto:
POST {{baseUrl}}/projetos
Content-Type: application/json

{
  "nome": "Projeto Teste",
  "responsavelId": 1,
  "subResponsavelId": 3,
  "nota": 9.5
}



### Buscar todos os Projetos:
GET {{baseUrl}}/projetos

### Buscar um Projeto por ID:
GET {{baseUrl}}/projetos/1

###Atualizar um Projeto:
PUT {{baseUrl}}/projetos/1
Content-Type: application/json

{
  "nome": "Projeto Atualizado",
  "responsavelId": 3,
  "subResponsavelId": 1,
  "resultado": "Projeto concluído com sucesso.",
  "entrega1": "2025-02-10",
  "entrega2": "2025-02-15",
  "entrega3": "2025-02-20",
  "nota": 8.7
}

###Deletar um Projeto:
DELETE {{baseUrl}}/projetos/1


##-------------------------------------------------------------
### ESCALA ROBO
### GET para obter escalas de todos os funcionários:
GET {{baseUrl}}/escalas

###POST para adicionar dias à escala de um funcionário:
POST {{baseUrl}}/escalas/adicionar/1
Content-Type: application/json

{
  "Datas": [
    "2025-01-22",
    "2025-01-23",
    "2025-01-24"
  ]
}



###DELETE para remover dias da escala de um funcionário:
DELETE {{baseUrl}}/escalas/remover/1
Content-Type: application/json

{
  "Datas": [
    "2025-02-22",
    "2025-02-23"
  ]
}








